import { Inter } from 'next/font/google'
import './globals.css'
import Cabecalho from '@/components/cabecalho'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Porto Seguro',
  description: 'Generated by FIAP',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Cabecalho/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
